### ISSUE TITLE
Missing functions tfd_matrix_diag_transform and tfd_fill_triangular

### ISSUE THREAD

**Issue by davidruegamer** [rstudio/tfprobability#126]
The documentation of `tfd_multivariate_normal_tri_l` and other multivariate normal distributions states that 

> Trainable (batch) lower-triangular matrices can be created with `tfd_matrix_diag_transform()` and/or `tfd_fill_triangular()`

If I am not mistaken, those functions are currently not avaiblable in the package?

**Comment by skeydan** [comment]
Hi,

thanks for noting this - I think the first of these does not exist any more, and the second really is a bijector: https://rstudio.github.io/tfprobability/reference/tfb_fill_triangular.html

I'll update the documentation.

**Comment by davidruegamer** [comment]
Perfect, thanks for the quick reply :+1:
