### ISSUE TITLE
Not all keras layer params are exposed

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/tfprobability#13]
E.g. currently we can't pass `activity_regularizer` to the tfp layers. We can expose all keras layer params or we can keep only the named params in the Python API and capture `...`.

(https://www.tensorflow.org/probability/api_docs/python/tfp/layers/MultivariateNormalTriL)

```
__init__(
    event_size,
    convert_to_tensor_fn=tfd.Distribution.sample,
    validate_args=False,
    **kwargs
)
```

```
function(object,
                event_size,
                convert_to_tensor_fn = tfp$distributions$Distribution$sample,
                validate_args = FALSE,
                ...)
```

**Comment by skeydan** [comment]
I've added `...` everywhere now (and removed existing `keras` params)

https://github.com/rstudio/tfprobability/pull/42

I see the point about input checking and completion, but honestly I think there's too much moving at the moment (in TF, TFK, TFP) so I suggest keeping that as an idea for a later time. Closing for now.
