### ISSUE TITLE
Implementing JointDistributionNamedAutoBatched

### ISSUE THREAD

**Issue by melondonkey** [rstudio/tfprobability#131]
It seems like this could help simplify modeling a good bit as I'm always having trouble with my dimensions.  Are there any plans to include this in a future release or is there a way to access it now?

**Comment by skeydan** [comment]
Hi, you're right, that absolutely should be added for the next release! Would you be interested in creating a PR?

The related `JointDistributionNamed` is here

https://github.com/rstudio/tfprobability/blob/758e1eec7d5fbb8632b601c26f521f9707bc859f/R/distributions.R#L3203


, and the corresponding test is here: 

https://github.com/rstudio/tfprobability/blob/758e1eec7d5fbb8632b601c26f521f9707bc859f/tests/testthat/test-distributions.R#L634

You could copy these and make the necessary modifications (documentation, parameters..) for the new variant.

**Comment by skeydan** [comment]
Just added this as part of https://github.com/rstudio/tfprobability/pull/134

(will be merged in the first half of this week, but if you need it ASAP you could check out from the PR)
